// components/input/input.svelte
<script lang="ts">
	import { classes } from "$lib/commons/utils/classes";

	let className: Maybe<string> = undefined;

	export { className as class };
	export let inputClass: Maybe<string> = undefined;
	export let label: Maybe<string> = undefined;
	export let value: Maybe<string> = undefined;
	export let readonly = false;
</script>

<div
	class={classes(
		"group grid border-b border-solid border-neutral-400 transition-all duration-200 focus-within:border-lime-500",
		className
	)}
>
	<div class="col-start-1 row-start-1 h-4" />

	<div
		class={classes(
			"pointer-events-none relative col-start-1 row-start-1 row-end-3 overflow-hidden",
			$$slots.icon && "mr-6"
		)}
	>
		{#if label}
			<div
				class={classes(
					"absolute top-4 origin-left whitespace-nowrap text-neutral-400 transition-all duration-200 group-focus-within:-translate-y-full group-focus-within:text-xs group-focus-within:text-lime-500",
					value && "-translate-y-full text-xs"
				)}
			>
				{label}
			</div>
		{/if}
	</div>

	<input
		bind:value
		on:focus
		on:blur
		on:click
		class={classes("col-start-1 row-start-2 box-border w-full", $$slots.icon && "pr-6", inputClass)}
		{readonly}
	/>

	<slot name="icon" class="pointer-events-none col-start-1 row-start-2 justify-self-end" />
</div>

// components/input/index.tsx
import { forwardRef } from "react";

import { classNames } from "commons/utils";

export type InputProps = React.InputHTMLAttributes<HTMLInputElement> & {
  label?: string;
  value?: string;
};

function Input(
  { label, className, value = "", ...props }: InputProps,
  ref: React.Ref<HTMLInputElement>
) {
  return (
    <div
      className={classNames(
        "group relative border-b border-solid border-neutral-400 py-1 transition-all duration-200 focus-within:border-lime-500",
        className
      )}
    >
      {label && (
        <div
          className={classNames(
            "pointer-events-none absolute top-5 origin-left text-neutral-400 transition-all duration-200 group-focus-within:-translate-y-full group-focus-within:text-xs group-focus-within:text-lime-500",
            value && "-translate-y-full text-xs"
          )}
        >
          {label}
        </div>
      )}
      <input
        ref={ref}
        value={value}
        className={classNames("w-full", label && "pt-4")}
        {...props}
      />
    </div>
  );
}

export default forwardRef(Input);
