// components/tooltip/tooltip.svelte
<script lang="ts">
	import { cubicInOut } from "svelte/easing";

	import { classes } from "$lib/commons/utils/classes";

	let className: Maybe<string> = undefined;

	export { className as class };
	export let show = false;

	const appear = (_: HTMLDivElement) => ({
		duration: 300,
		easing: cubicInOut,
		css: (t: number) => `
      scale: ${t / 2 + 0.5};
      opacity: ${t};
    `,
	});
</script>

<span class={classes(className, "relative")}>
	<slot />

	{#if show}
		<div transition:appear class="absolute z-10 w-full rounded bg-zinc-900 pb-4 pt-4 shadow">
			<slot name="tooltip" />
		</div>
	{/if}
</span>

// components/tooltip/index.tsx
import Transition from "commons/components/transition";
import { classNames } from "commons/utils";

export default function Tooltip({
  children,
  show,
  content,
  className,
  contentClassName,
}: {
  children: React.ReactNode;
  show: boolean;
  content: React.ReactNode;
  className?: string;
  contentClassName?: string;
}) {
  return (
    <span className={className}>
      {children}
      <Transition
        show={show}
        className="relative z-10 scale-50 opacity-0"
        transitionClassName="[&]:scale-100 [&]:opacity-100"
      >
        <div
          className={classNames(
            "absolute w-full rounded bg-zinc-900 p-4 shadow",
            contentClassName
          )}
        >
          {content}
        </div>
      </Transition>
    </span>
  );
}
