// components/snackbar/index.tsx
"use client";

import { useEffect, useState } from "react";

import Transition from "commons/components/transition";
import { classNames } from "commons/utils";
import { removeMessage, useMessages } from "./messages";

const DELAY = 3000;

export { addMessage } from "./messages";

export default function Snackbar() {
  const [message] = useMessages();
  const [show, setShow] = useState(false);

  const handleTransitionEnd = (
    { propertyName }: React.TransitionEvent<HTMLDivElement>,
    transition: boolean
  ) => {
    if (propertyName !== "opacity") {
      return;
    }

    if (transition) {
      setTimeout(() => {
        setShow(false);
      }, DELAY);
    } else {
      removeMessage();
    }
  };

  useEffect(() => {
    setShow(!!message);
  }, [message]);

  return (
    <Transition
      show={show}
      className={classNames(
        "fixed bottom-0 left-1/2 -translate-x-1/2 translate-y-full rounded p-3 opacity-0",
        message?.type === "error" ? "bg-red-700" : "bg-lime-500 text-black"
      )}
      transitionClassName="[&]:-translate-y-10 [&]:opacity-100"
      onTransitionEnd={handleTransitionEnd}
    >
      {message?.text}
    </Transition>
  );
}

// components/snackbar/snackbar.svelte
<script lang="ts">
	import { portal } from "$lib/commons/utils/portal";
	import { fly } from "svelte/transition";
	import { store, types } from "./store";

	const DELAY = 3000;

	$: message = $store[0];

	$: error = message?.type === types.ERROR;

	let show = true;

	const handleIn = () => {
		setTimeout(() => {
			show = false;
		}, DELAY);
	};

	const handleOut = () => {
		$store.shift();
		$store = $store;
		show = true;
	};
</script>

{#if message && show}
	<div
		use:portal
		class="container"
		class:error
		on:introend={handleIn}
		on:outroend={handleOut}
		transition:fly={{ y: "100%" }}
	>
		{message.text}
	</div>
{/if}

<style lang="scss">
	@use "src/lib/commons/theme";

	.container {
		position: fixed;
		bottom: 1rem;
		left: 50%;
		translate: -50%;
		border-radius: 0.25rem;
		background: theme.$colorPrimary;
		padding: 1rem;
		color: black;
	}

	.error {
		background: theme.$colorError;
		color: white;
	}
</style>
